// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Part interface {
	IsPart()
}

type AgentMessage struct {
	Parts        []Part  `json:"parts"`
	MessageType  *string `json:"messageType,omitempty"`
	MessageState *string `json:"messageState,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type TextPart struct {
	Text string `json:"text"`
}

func (TextPart) IsPart() {}
