// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Part interface {
	IsPart()
}

type AgentResponse struct {
	Parts         []Part  `json:"parts"`
	ResponseType  *string `json:"responseType,omitempty"`
	ResponseState *string `json:"responseState,omitempty"`
}

type FilePart struct {
	Name     string  `json:"name"`
	MimeType string  `json:"mimeType"`
	Bytes    *string `json:"bytes,omitempty"`
	URI      *string `json:"uri,omitempty"`
}

func (FilePart) IsPart() {}

type Query struct {
}

type Subscription struct {
}

type TaskInput struct {
	ID        *string `json:"id,omitempty"`
	ContextID string  `json:"contextId"`
	Message   string  `json:"message"`
}

type TextPart struct {
	Text string `json:"text"`
}

func (TextPart) IsPart() {}
